name: lint-and-test

on: push

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install deps
        run: |
          pip install poetry coveralls
          poetry install
          cd ui && yarn --frozen-lockfile

      - name: Run linters
        run: |
          bash misc/lint.sh --check

      - name: Run tests
        run: |
          poetry run coverage run -m ward
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
